import React, { useState, useMemo } from 'react';
import { 
  Wrench, Palette, Image as ImageIcon, Sliders, Check, Copy, Download, 
  Terminal, ShieldCheck, RefreshCw, Eye, Sparkles, Layers, Type, Maximize2, FileText, Code
} from 'lucide-react';

export default function ToolsSection() {
  const [activeTab, setActiveTab] = useState('colour'); // 'colour', 'img', 'svg', 'calc', 'cli'

  // --- 1. COLOR CONVERTER STATE ---
  const [hexColor, setHexColor] = useState('#BAFDC1');
  const [copiedCode, setCopiedCode] = useState(null);

  // Convert HEX to RGB, HSL, OKLCH approximations
  const colorData = useMemo(() => {
    let cleanHex = hexColor.replace('#', '');
    if (cleanHex.length === 3) {
      cleanHex = cleanHex.split('').map(c => c + c).join('');
    }
    if (cleanHex.length !== 6) cleanHex = 'BAFDC1';

    const r = parseInt(cleanHex.substring(0, 2), 16) || 0;
    const g = parseInt(cleanHex.substring(2, 4), 16) || 0;
    const b = parseInt(cleanHex.substring(4, 6), 16) || 0;

    // HSL
    const rNorm = r / 255, gNorm = g / 255, bNorm = b / 255;
    const max = Math.max(rNorm, gNorm, bNorm), min = Math.min(rNorm, gNorm, bNorm);
    let h = 0, s = 0, l = (max + min) / 2;

    if (max !== min) {
      const d = max - min;
      s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
      switch (max) {
        case rNorm: h = (gNorm - bNorm) / d + (gNorm < bNorm ? 6 : 0); break;
        case gNorm: h = (bNorm - rNorm) / d + 2; break;
        case bNorm: h = (rNorm - gNorm) / d + 4; break;
      }
      h /= 6;
    }
    const hDeg = Math.round(h * 360);
    const sPct = Math.round(s * 100);
    const lPct = Math.round(l * 100);

    // Approximate OKLCH Lightness, Chroma, Hue
    const oklchL = (0.2126 * rNorm + 0.7152 * gNorm + 0.0722 * bNorm).toFixed(3);
    const oklchC = (Math.sqrt(Math.pow(rNorm - gNorm, 2) + Math.pow(gNorm - bNorm, 2)) * 0.15).toFixed(3);

    return {
      hex: `#${cleanHex.toUpperCase()}`,
      rgb: `rgb(${r}, ${g}, ${b})`,
      hsl: `hsl(${hDeg}, ${sPct}%, ${lPct}%)`,
      oklch: `oklch(${oklchL} ${oklchC} ${hDeg})`,
      r, g, b, h: hDeg, s: sPct, l: lPct
    };
  }, [hexColor]);

  // Tailwind Shades Generator (50 to 950)
  const tailwindShades = useMemo(() => {
    const shades = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
    return shades.map(weight => {
      const factor = (500 - weight) / 500;
      let r = colorData.r, g = colorData.g, b = colorData.b;
      if (factor > 0) {
        // Lighter towards 50
        r = Math.round(r + (255 - r) * factor * 0.85);
        g = Math.round(g + (255 - g) * factor * 0.85);
        b = Math.round(b + (255 - b) * factor * 0.85);
      } else {
        // Darker towards 950
        const darkFactor = Math.abs(factor);
        r = Math.round(r * (1 - darkFactor * 0.85));
        g = Math.round(g * (1 - darkFactor * 0.85));
        b = Math.round(b * (1 - darkFactor * 0.85));
      }
      const hex = `#${((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1).toUpperCase()}`;
      return { weight, hex };
    });
  }, [colorData]);

  // Contrast Ratio Checker
  const contrastRatio = useMemo(() => {
    const getLuminance = (r, g, b) => {
      const a = [r, g, b].map(v => {
        v /= 255;
        return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
      });
      return a[0] * 0.2126 + a[1] * 0.7152 + a[2] * 0.0722;
    };
    const lumColor = getLuminance(colorData.r, colorData.g, colorData.b);
    const lumBg = getLuminance(17, 17, 20); // Dark base background luminance
    const ratio = (Math.max(lumColor, lumBg) + 0.05) / (Math.min(lumColor, lumBg) + 0.05);
    return ratio.toFixed(2);
  }, [colorData]);

  // --- 2. SVG OPTIMIZER STATE ---
  const [rawSvg, setRawSvg] = useState(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <!-- Generated by Kalpagrafica SVGO -->
  <g id="Layer_1" data-name="Layer 1">
    <path fill="#BAFDC1" d="M50 10 L90 90 L10 90 Z" />
    <circle cx="50" cy="60" r="15" fill="#111114" />
  </g>
</svg>`);

  const optimizedSvg = useMemo(() => {
    let clean = rawSvg;
    // Remove comments
    clean = clean.replace(/<!--[\s\S]*?-->/g, '');
    // Remove metadata & title tags
    clean = clean.replace(/<title>[\s\S]*?<\/title>/gi, '');
    clean = clean.replace(/<desc>[\s\S]*?<\/desc>/gi, '');
    // Remove id and data-name attributes
    clean = clean.replace(/\s+(id|data-name)="[^"]*"/gi, '');
    // Collapse multiple whitespace
    clean = clean.replace(/\s+/g, ' ').replace(/> </g, '><').trim();
    return clean;
  }, [rawSvg]);

  // --- 3. ASPECT RATIO & TYPE CALC STATE ---
  const [baseWidth, setBaseWidth] = useState(1920);
  const [baseHeight, setBaseHeight] = useState(1080);
  const [newWidth, setNewWidth] = useState(1080);
  const calculatedHeight = useMemo(() => {
    if (!baseWidth || !baseHeight || !newWidth) return 0;
    return Math.round((newWidth * baseHeight) / baseWidth);
  }, [baseWidth, baseHeight, newWidth]);

  // Type Scale Calculator
  const [baseFontSize, setBaseFontSize] = useState(16);
  const [scaleRatio, setScaleRatio] = useState(1.25); // 1.25 Major Third
  const fontScaleList = useMemo(() => {
    const steps = [-2, -1, 0, 1, 2, 3, 4, 5];
    return steps.map(step => {
      const px = Math.round(baseFontSize * Math.pow(scaleRatio, step));
      const rem = (px / 16).toFixed(3);
      return { step, px, rem };
    });
  }, [baseFontSize, scaleRatio]);

  const copyToClipboard = (text, id) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(id);
    setTimeout(() => setCopiedCode(null), 2000);
  };

  return (
    <section className="section-container" style={{ paddingTop: '3rem', paddingBottom: '5rem' }}>
      {/* Section Header */}
      <div style={{ textAlign: 'center', maxWidth: '850px', margin: '0 auto 3rem' }}>
        <div className="font-caps" style={{ 
          display: 'inline-flex', 
          alignItems: 'center', 
          gap: '0.5rem', 
          color: 'var(--accent)', 
          backgroundColor: 'var(--accent-muted)',
          padding: '0.4rem 1rem',
          borderRadius: 'var(--radius-full)',
          marginBottom: '1rem',
          border: '1px solid rgba(186,253,193,0.3)'
        }}>
          <Wrench size={15} />
          <span>KalpaTools & Delphi CLI Suite</span>
        </div>

        <h2 className="font-headline" style={{ 
          fontSize: 'clamp(2rem, 4vw, 3.2rem)', 
          fontWeight: 700, 
          letterSpacing: '-0.02em', 
          color: 'var(--text-primary)',
          lineHeight: 1.15,
          marginBottom: '1.2rem'
        }}>
          Herramientas de Diseño
        </h2>

        <p style={{ 
          color: 'var(--text-secondary)', 
          fontSize: '1.05rem', 
          lineHeight: 1.6 
        }}>
          Suite utilitaria offline para diseñadores y desarrolladores: colorimetría OKLCH, conversión de formato, optimización SVG, escalas tipográficas y comandos para la terminal <strong style={{ color: 'var(--accent)' }}>delphitools-cli</strong>.
        </p>
      </div>

      {/* Navigation Tabs Bar */}
      <div style={{
        display: 'flex',
        justifyContent: 'center',
        gap: '0.6rem',
        flexWrap: 'wrap',
        marginBottom: '2.5rem'
      }}>
        {[
          { id: 'colour', label: 'Color & Paletas', icon: Palette },
          { id: 'svg', label: 'Optimizador SVG', icon: Code },
          { id: 'img', label: 'Social & Cropper', icon: ImageIcon },
          { id: 'calc', label: 'Escala & Aspect Ratio', icon: Sliders },
          { id: 'cli', label: 'Comandos CLI (Terminal)', icon: Terminal }
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className="font-caps"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.5rem',
                padding: '0.6rem 1.2rem',
                borderRadius: 'var(--radius-md)',
                border: isActive ? '1px solid var(--accent)' : '1px solid var(--border-subtle)',
                backgroundColor: isActive ? 'var(--accent)' : 'var(--bg-surface)',
                color: isActive ? '#08080A' : 'var(--text-secondary)',
                fontWeight: isActive ? 700 : 500,
                fontSize: '0.85rem',
                cursor: 'pointer',
                transition: 'all 0.25s ease',
                boxShadow: isActive ? '0 4px 15px rgba(186, 253, 193, 0.2)' : 'none'
              }}
            >
              <Icon size={16} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* TAB 1: COLOR & PALETTES */}
      {activeTab === 'colour' && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '2rem' }}>
          {/* Color Picker & Live Formats */}
          <div style={{
            backgroundColor: 'var(--bg-surface)',
            borderRadius: 'var(--radius-lg)',
            border: '1px solid var(--border-subtle)',
            padding: '2rem',
            boxShadow: 'var(--shadow-subtle)'
          }}>
            <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Palette size={18} color="var(--accent)" />
              <span>Conversor de Color Multi-Espacio</span>
            </h3>

            {/* Input Picker & Swatch */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '1.2rem', marginBottom: '1.8rem' }}>
              <input
                type="color"
                value={hexColor}
                onChange={(e) => setHexColor(e.target.value)}
                style={{
                  width: '64px',
                  height: '64px',
                  borderRadius: 'var(--radius-md)',
                  border: '2px solid var(--accent)',
                  cursor: 'pointer',
                  backgroundColor: 'transparent'
                }}
              />
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.3rem' }}>
                  HEX Color
                </label>
                <input
                  type="text"
                  value={hexColor}
                  onChange={(e) => setHexColor(e.target.value)}
                  className="input font-mono"
                  style={{ width: '100%', fontSize: '1.1rem', fontWeight: 700 }}
                />
              </div>
            </div>

            {/* Color Format Output List */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
              {[
                { label: 'HEX', val: colorData.hex },
                { label: 'RGB', val: colorData.rgb },
                { label: 'HSL', val: colorData.hsl },
                { label: 'OKLCH', val: colorData.oklch }
              ].map((fmt) => (
                <div key={fmt.label} style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  backgroundColor: 'var(--bg-surface-2)',
                  padding: '0.7rem 1rem',
                  borderRadius: 'var(--radius-sm)',
                  border: '1px solid var(--border-subtle)'
                }}>
                  <div>
                    <span className="font-mono" style={{ fontSize: '0.75rem', color: 'var(--text-disabled)', display: 'block' }}>{fmt.label}</span>
                    <strong className="font-mono" style={{ fontSize: '0.92rem', color: 'var(--accent)' }}>{fmt.val}</strong>
                  </div>
                  <button
                    className="btn btn-ghost btn-sm"
                    onClick={() => copyToClipboard(fmt.val, fmt.label)}
                    title="Copiar formato"
                  >
                    {copiedCode === fmt.label ? <Check size={16} color="var(--accent)" /> : <Copy size={16} />}
                  </button>
                </div>
              ))}
            </div>

            {/* Contrast Ratio Result */}
            <div style={{
              marginTop: '1.8rem',
              padding: '1rem',
              borderRadius: 'var(--radius-md)',
              backgroundColor: 'var(--bg-surface-2)',
              border: '1px solid var(--border-subtle)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between'
            }}>
              <div>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block' }}>Ratio de Contraste vs Fondo Oscuro</span>
                <strong className="font-mono" style={{ fontSize: '1.2rem', color: Number(contrastRatio) >= 4.5 ? 'var(--accent)' : '#F87171' }}>
                  {contrastRatio}:1 {Number(contrastRatio) >= 4.5 ? '✓ (AA/AAA Pass)' : '⚠ (Bajo Contraste)'}
                </strong>
              </div>
            </div>
          </div>

          {/* Tailwind Shade Generator Scale */}
          <div style={{
            backgroundColor: 'var(--bg-surface)',
            borderRadius: 'var(--radius-lg)',
            border: '1px solid var(--border-subtle)',
            padding: '2rem',
            boxShadow: 'var(--shadow-subtle)'
          }}>
            <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Layers size={18} color="var(--accent)" />
              <span>Escala de Sombras Tailwind (50 — 950)</span>
            </h3>

            <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>
              Genera una paleta de 11 niveles de brillo calculados matemáticamente para tu sistema de diseño.
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {tailwindShades.map((shade) => (
                <div
                  key={shade.weight}
                  onClick={() => copyToClipboard(shade.hex, `shade-${shade.weight}`)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    backgroundColor: shade.hex,
                    color: shade.weight < 500 ? '#08080A' : '#FFFFFF',
                    padding: '0.6rem 1rem',
                    borderRadius: 'var(--radius-sm)',
                    cursor: 'pointer',
                    fontWeight: 600,
                    fontSize: '0.85rem',
                    transition: 'transform 0.15s ease'
                  }}
                  className="shade-item"
                >
                  <span className="font-mono">{shade.weight}</span>
                  <span className="font-mono">{shade.hex}</span>
                  {copiedCode === `shade-${shade.weight}` ? <Check size={15} /> : <Copy size={15} style={{ opacity: 0.7 }} />}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: SVG OPTIMIZER */}
      {activeTab === 'svg' && (
        <div style={{
          backgroundColor: 'var(--bg-surface)',
          borderRadius: 'var(--radius-lg)',
          border: '1px solid var(--border-subtle)',
          padding: '2rem',
          boxShadow: 'var(--shadow-subtle)'
        }}>
          <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Code size={18} color="var(--accent)" />
            <span>Optimizador & Limpiador SVG (SVGO)</span>
          </h3>

          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>
            Limpia etiquetas basura (<code>&lt;title&gt;</code>, <code>&lt;desc&gt;</code>, <code>id</code>, metadata de Illustrator/Inkscape) y comprime el código vectorial.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem' }}>
            {/* Input SVG Code */}
            <div>
              <label style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.4rem' }}>
                SVG Original ({rawSvg.length} bytes)
              </label>
              <textarea
                value={rawSvg}
                onChange={(e) => setRawSvg(e.target.value)}
                className="input font-mono"
                rows={12}
                style={{ width: '100%', fontSize: '0.82rem', lineHeight: 1.4 }}
                placeholder="Pega aquí el código <svg>..."
              />
            </div>

            {/* Optimized SVG Output */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.4rem' }}>
                <label style={{ fontSize: '0.82rem', color: 'var(--accent)' }}>
                  SVG Optimizado ({optimizedSvg.length} bytes)
                </label>
                <span className="font-mono" style={{ fontSize: '0.78rem', color: 'var(--accent)' }}>
                  Ahorro: {Math.max(0, Math.round((1 - optimizedSvg.length / (rawSvg.length || 1)) * 100))}%
                </span>
              </div>
              <textarea
                readOnly
                value={optimizedSvg}
                className="input font-mono"
                rows={12}
                style={{ width: '100%', fontSize: '0.82rem', lineHeight: 1.4, backgroundColor: 'var(--bg-surface-2)' }}
              />
              <button
                className="btn btn-primary btn-sm"
                onClick={() => copyToClipboard(optimizedSvg, 'svg-opt')}
                style={{ marginTop: '0.8rem', width: '100%', justifyContent: 'center' }}
              >
                {copiedCode === 'svg-opt' ? <Check size={16} /> : <Copy size={16} />}
                <span>{copiedCode === 'svg-opt' ? '¡Código SVG Copiado!' : 'Copiar SVG Optimizado'}</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: SOCIAL CROPPER & MATTE */}
      {activeTab === 'img' && (
        <div style={{
          backgroundColor: 'var(--bg-surface)',
          borderRadius: 'var(--radius-lg)',
          border: '1px solid var(--border-subtle)',
          padding: '2rem',
          boxShadow: 'var(--shadow-subtle)'
        }}>
          <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <ImageIcon size={18} color="var(--accent)" />
            <span>Social Cropper & Generador de Marcos / Matte</span>
          </h3>

          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '1.8rem' }}>
            Recorta y enmarca imágenes para plataformas de redes sociales con márgenes limpios y proporciones estándar.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '1.2rem' }}>
            {[
              { ratio: '1:1', title: 'Instagram Post / Avatares', dim: '1080 x 1080 px' },
              { ratio: '4:5', title: 'Instagram Portrait', dim: '1080 x 1350 px' },
              { ratio: '16:9', title: 'YouTube / Banner Landscape', dim: '1920 x 1080 px' },
              { ratio: '9:16', title: 'TikTok / Instagram Reels', dim: '1080 x 1920 px' }
            ].map((item) => (
              <div key={item.ratio} style={{
                backgroundColor: 'var(--bg-surface-2)',
                border: '1px solid var(--border-subtle)',
                borderRadius: 'var(--radius-md)',
                padding: '1.2rem',
                textAlign: 'center'
              }}>
                <div className="font-mono" style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--accent)', marginBottom: '0.3rem' }}>
                  {item.ratio}
                </div>
                <strong style={{ fontSize: '0.9rem', color: 'var(--text-primary)', display: 'block', marginBottom: '0.2rem' }}>
                  {item.title}
                </strong>
                <span className="font-mono" style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                  {item.dim}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 4: CALC & TYPE SCALE */}
      {activeTab === 'calc' && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '2rem' }}>
          {/* Aspect Ratio Calc */}
          <div style={{
            backgroundColor: 'var(--bg-surface)',
            borderRadius: 'var(--radius-lg)',
            border: '1px solid var(--border-subtle)',
            padding: '2rem',
            boxShadow: 'var(--shadow-subtle)'
          }}>
            <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Maximize2 size={18} color="var(--accent)" />
              <span>Calculadora de Aspect Ratio</span>
            </h3>

            <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.2rem' }}>
              <div>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.3rem' }}>Ancho Base (W1)</label>
                <input
                  type="number"
                  value={baseWidth}
                  onChange={(e) => setBaseWidth(Number(e.target.value))}
                  className="input font-mono"
                  style={{ width: '100%' }}
                />
              </div>
              <div>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.3rem' }}>Alto Base (H1)</label>
                <input
                  type="number"
                  value={baseHeight}
                  onChange={(e) => setBaseHeight(Number(e.target.value))}
                  className="input font-mono"
                  style={{ width: '100%' }}
                />
              </div>
            </div>

            <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.3rem' }}>Nuevo Ancho (W2)</label>
                <input
                  type="number"
                  value={newWidth}
                  onChange={(e) => setNewWidth(Number(e.target.value))}
                  className="input font-mono"
                  style={{ width: '100%' }}
                />
              </div>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '0.8rem', color: 'var(--accent)', display: 'block', marginBottom: '0.3rem' }}>Alto Calculado (H2)</label>
                <div className="input font-mono" style={{ backgroundColor: 'var(--bg-surface-2)', fontWeight: 700, color: 'var(--accent)' }}>
                  {calculatedHeight} px
                </div>
              </div>
            </div>
          </div>

          {/* Modular Type Scale Calc */}
          <div style={{
            backgroundColor: 'var(--bg-surface)',
            borderRadius: 'var(--radius-lg)',
            border: '1px solid var(--border-subtle)',
            padding: '2rem',
            boxShadow: 'var(--shadow-subtle)'
          }}>
            <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Type size={18} color="var(--accent)" />
              <span>Escala Tipográfica Modular</span>
            </h3>

            <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.2rem' }}>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.3rem' }}>Base (px)</label>
                <input
                  type="number"
                  value={baseFontSize}
                  onChange={(e) => setBaseFontSize(Number(e.target.value))}
                  className="input font-mono"
                  style={{ width: '100%' }}
                />
              </div>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.3rem' }}>Proporción</label>
                <select
                  value={scaleRatio}
                  onChange={(e) => setScaleRatio(Number(e.target.value))}
                  className="input font-mono"
                  style={{ width: '100%', backgroundColor: 'var(--bg-surface-2)' }}
                >
                  <option value={1.125}>1.125 — Major Second</option>
                  <option value={1.200}>1.200 — Minor Third</option>
                  <option value={1.250}>1.250 — Major Third</option>
                  <option value={1.414}>1.414 — Aug Fourth</option>
                  <option value={1.618}>1.618 — Golden Ratio</option>
                </select>
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              {fontScaleList.map(item => (
                <div key={item.step} style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '0.4rem 0.8rem',
                  backgroundColor: 'var(--bg-surface-2)',
                  borderRadius: 'var(--radius-sm)',
                  border: '1px solid var(--border-subtle)'
                }}>
                  <span className="font-mono" style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>Nivel {item.step > 0 ? `+${item.step}` : item.step}</span>
                  <strong className="font-mono" style={{ fontSize: '0.9rem', color: 'var(--accent)' }}>{item.px} px</strong>
                  <span className="font-mono" style={{ fontSize: '0.78rem', color: 'var(--text-disabled)' }}>{item.rem} rem</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* TAB 5: CLI TERMINAL REFERENCE */}
      {activeTab === 'cli' && (
        <div style={{
          backgroundColor: 'var(--bg-surface)',
          borderRadius: 'var(--radius-lg)',
          border: '1px solid var(--border-subtle)',
          padding: '2rem',
          boxShadow: 'var(--shadow-subtle)'
        }}>
          <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Terminal size={18} color="var(--accent)" />
            <span>delphitools-cli — Guía de Comandos para Terminal</span>
          </h3>

          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>
            Ejecuta las mismas herramientas en tu terminal Linux/Mac/Windows de forma 100% offline y sin telemetría.
          </p>

          <div style={{
            backgroundColor: '#08080A',
            border: '1px solid var(--border-strong)',
            borderRadius: 'var(--radius-md)',
            padding: '1.5rem',
            marginBottom: '1.5rem'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.8rem' }}>
              <span className="font-mono" style={{ fontSize: '0.8rem', color: 'var(--text-disabled)' }}>Instalación vía Cargo / Rust</span>
              <button
                className="btn btn-ghost btn-sm"
                onClick={() => copyToClipboard('cargo install delphitools-cli', 'cargo-ins')}
              >
                {copiedCode === 'cargo-ins' ? <Check size={15} color="var(--accent)" /> : <Copy size={15} />}
              </button>
            </div>
            <code className="font-mono" style={{ color: 'var(--accent)', fontSize: '0.95rem', display: 'block' }}>
              cargo install delphitools-cli
            </code>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.2rem' }}>
            {[
              { cmd: 'dt colour #BAFDC1 -j', desc: 'Convierte color a HEX, RGB, HSL, OKLCH en JSON' },
              { cmd: 'dt tailwind-shades #BAFDC1', desc: 'Genera escala de sombras 50-950 en la consola' },
              { cmd: 'dt svgo logo.svg -o clean.svg', desc: 'Optimiza y remueve metadata de un archivo SVG' },
              { cmd: 'dt crop image.jpg --ratio 1:1', desc: 'Corta imagen a proporción 1:1 o 16:9' },
              { cmd: 'dt contrast #BAFDC1 #111114', desc: 'Calcula ratio de contraste WCAG AA/AAA' },
              { cmd: 'dt favicon logo.svg', desc: 'Genera iconos favicons para la web (16, 32, 180, 512px)' }
            ].map((c) => (
              <div key={c.cmd} style={{
                backgroundColor: 'var(--bg-surface-2)',
                border: '1px solid var(--border-subtle)',
                borderRadius: 'var(--radius-md)',
                padding: '1rem'
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.4rem' }}>
                  <code className="font-mono" style={{ fontSize: '0.82rem', color: 'var(--accent)' }}>{c.cmd}</code>
                  <button
                    className="btn btn-ghost btn-sm"
                    onClick={() => copyToClipboard(c.cmd, c.cmd)}
                    style={{ padding: '0.2rem' }}
                  >
                    {copiedCode === c.cmd ? <Check size={14} color="var(--accent)" /> : <Copy size={14} />}
                  </button>
                </div>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block' }}>{c.desc}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <style>{`
        .shade-item:hover {
          transform: scale(1.02);
        }
      `}</style>
    </section>
  );
}
