import React, { useState, useMemo } from 'react';
import { Code, Check, Copy, Download } from 'lucide-react';
import { ToolCard, FieldLabel, UploadZone } from './CommonComponents';
import { loadSvgTextFromFile, optimizeSvgCode, downloadTextFile } from '../../utils/image';

export default function SvgTab({ copiedCode, copyToClipboard }) {
  const [svgFileName, setSvgFileName] = useState('');
  const [rawSvg, setRawSvg] = useState(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="120" height="120">
  <!-- Generated by Kalpagrafica SVGO -->
  <g id="Layer_1" data-name="Layer 1">
    <polygon points="50,10 90,90 10,90" fill="#BAFDC1" />
    <circle cx="50" cy="60" r="15" fill="#111114" />
  </g>
</svg>`);

  const handleSvgUpload = async (file) => {
    setSvgFileName(file.name);
    const text = await loadSvgTextFromFile(file);
    setRawSvg(text);
  };

  const optimizedSvg = useMemo(() => {
    return optimizeSvgCode(rawSvg);
  }, [rawSvg]);

  const downloadOptimizedSvg = () => {
    const filename = svgFileName ? svgFileName.replace(/\.svg$/i, '-optimizado.svg') : 'kalpa-vector-optimizado.svg';
    downloadTextFile(optimizedSvg, filename, 'image/svg+xml;charset=utf-8');
  };

  return (
    <ToolCard icon={Code} title="Optimizador & Limpiador SVG (SVGO)" description={<>Limpia metadata y comprime el código vectorial de cualquier archivo .svg preservando las referencias id internas para no deformar el diseño.</>}>
      <div style={{ marginBottom: '1.5rem' }}>
        <FieldLabel accent>Subí un archivo SVG (Logo, Marca o Ilustración Vectorial)</FieldLabel>
        <UploadZone
          onFile={handleSvgUpload}
          fileName={svgFileName}
          accept=".svg,image/svg+xml"
          hint="Arrastrá tu archivo .svg para leer y limpiar su código automáticamente"
        />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem' }}>
        <div>
          <FieldLabel>SVG Original ({rawSvg.length} bytes)</FieldLabel>
          <textarea
            value={rawSvg}
            onChange={(e) => setRawSvg(e.target.value)}
            className="input font-mono"
            rows={10}
            style={{ width: '100%', fontSize: '0.82rem', lineHeight: 1.4 }}
            placeholder="Pega aquí el código <svg> o sube un archivo..."
          />
        </div>
        <div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.4rem' }}>
            <label style={{ fontSize: '0.82rem', color: 'var(--accent)', fontWeight: 600 }}>SVG Optimizado ({optimizedSvg.length} bytes)</label>
            <span className="font-mono" style={{ fontSize: '0.78rem', color: 'var(--accent)' }}>
              Ahorro: {Math.max(0, Math.round((1 - optimizedSvg.length / (rawSvg.length || 1)) * 100))}%
            </span>
          </div>
          <textarea readOnly value={optimizedSvg} className="input font-mono" rows={10} style={{ width: '100%', fontSize: '0.82rem', lineHeight: 1.4, backgroundColor: 'var(--bg-surface-2)', marginBottom: '1rem' }} />
          
          <FieldLabel accent>Vista Previa Gráfica en Tiempo Real</FieldLabel>
          <div
            style={{
              border: '1px solid var(--border-subtle)',
              borderRadius: 'var(--radius-md)',
              padding: '1rem',
              backgroundColor: 'var(--bg-surface-2)',
              minHeight: '140px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              marginBottom: '1rem'
            }}
            dangerouslySetInnerHTML={{ __html: optimizedSvg }}
          />

          <div style={{ display: 'flex', gap: '0.8rem' }}>
            <button className="btn btn-primary btn-sm" onClick={() => copyToClipboard(optimizedSvg, 'svg-opt')} style={{ flex: 1, justifyContent: 'center' }}>
              {copiedCode === 'svg-opt' ? <Check size={16} /> : <Copy size={16} />}
              <span>{copiedCode === 'svg-opt' ? '¡Código Copiado!' : 'Copiar SVG'}</span>
            </button>
            <button className="btn btn-ghost btn-sm" onClick={downloadOptimizedSvg} style={{ flex: 1, justifyContent: 'center', border: '1px solid var(--accent)', color: 'var(--accent)' }}>
              <Download size={16} />
              <span>Descargar .SVG</span>
            </button>
          </div>
        </div>
      </div>
    </ToolCard>
  );
}
